### ISSUE TITLE
AUC negative when direction = ">"

### ISSUE THREAD

**Issue by bengouts** [abichat/evabic#4]
Hey,

It's **not** a big issue, but I got a negative AUC while trying to use `ebc_AUC` with the parameter ` direction = ">"`.
A minimal example would be, with your example from the README :
`ebc_AUC(detection_values = 1-pvalues, true = predictors, m = 7, direction = ">")`

Merci pour le package, qui m'a été utile ! 
Benoit

**Comment by abichat** [comment]
Fixed! It was because area was computed from right to left 
Thanks a lot for your feedback!
